Prevent deprecations causing errors
In order to work in a browser environment, `typeof` should be used to
check for a global that might not exist. This solves the `Uncaught
ReferenceError: process is not defined` error.

Resolves #140